"""add coluna nome na tabela usuario

Revision ID: b0bd408e2b4c
Revises: 2206929d4782
Create Date: 2026-05-08 15:56:29.567960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd408e2b4c'
down_revision: Union[str, Sequence[str], None] = '2206929d4782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
